"""Sphinx documentation generator configuration file.

The full set of configuration options is listed on the Sphinx website:
http://sphinx-doc.org/config.html

"""
import os
import sys

from packaging.version import Version


# Add the NailGun root directory to the system path. This allows references
# such as :mod:`nailgun.client` to be processed correctly.
ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), os.path.pardir))
sys.path.insert(0, ROOT_DIR)

# Parse the version according to PEP 440. Documentation is generated by Travis
# and an InvalidVersion is raised if the version is non-conformant, so this
# serves as a unit test for the contents of the `VERSION` file.
with open(os.path.join(ROOT_DIR, 'VERSION')) as handle:
    VERSION = Version(handle.read().strip())


# Project Information ---------------------------------------------------------

project = 'NailGun'
copyright = '2014, Jeremy Audet'
version = VERSION.base_version  # e.g. '1.2'
release = str(VERSION)  # e.g. '1.2a3.dev4'

# General Configuration -------------------------------------------------------

extensions = [
    'sphinx.ext.autodoc',
]
source_suffix = '.rst'
master_doc = 'index'
exclude_patterns = ['_build']
nitpicky = True
autodoc_default_options = {'members': None}

# Format-Specific Options -----------------------------------------------------

htmlhelp_basename = 'NailGundoc'
latex_documents = [
    (master_doc, f'{project}.tex', f'{project} Documentation', 'Jeremy Audet', 'manual')
]
man_pages = [
    (
        master_doc,
        project.lower(),
        f'{project} Documentation',
        ['Jeremy Audet'],
        1,  # man pages section
    )
]
texinfo_documents = [
    (
        master_doc,
        project,
        f'{project} Documentation',
        'Jeremy Audet',
        project,
        (
            'NailGun is a GPL-licensed Python library that facilitates easy usage of '
            'the Satellite 6 API.'
        ),
        'Miscellaneous',
    )
]
