# CI stages to execute against master branch on PR merge
name: update_nailgun_package_to_PyPI

on:
  push:
    branches:
      - master

env:
    PYCURL_SSL_LIBRARY: openssl

jobs:
  codechecks:
    name: Code Quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    steps:
      - name: Checkout Nailgun
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set Up Python-${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt-get install -y libgnutls28-dev libcurl4-openssl-dev libssl-dev
          # link vs compile time ssl implementations can break the environment when installing requirements
          # Uninstall pycurl - its likely not installed, but in case the ubuntu-latest packages change
          # Then compile and install it with PYCURL_SSL_LIBRARY set to openssl
          pip install -U pip
          pip uninstall -y pycurl
          pip install --compile --no-cache-dir pycurl
          pip install -U -r requirements.txt -r requirements-dev.txt --no-cache-dir

      - name: Pre Commit Checks
        uses: pre-commit/action@v2.0.0

      - name: Test Nailgun Coverage
        run: |
          make test-coverage

      - name: Make Docs
        run: |
          make docs-html
          make docs-clean

      - name: Make Package
        run: |
          make package
          make package-clean

      - name: Analysis (git diff)
        if: failure()
        run: git diff

      - name: Upload Codecov Coverage
        uses: codecov/codecov-action@v1.0.13
        with:
          fail_ci_if_error: true

  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Install pypa/build
        run: python -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/ .
      - name: Publish distribution 📦 to Test PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: satqeauto
          password: ${{ secrets.PYPI_PASSWORD }}
