# CI stages to execute against Pull Requests
name: Nailgun - CI

on:
  pull_request:
    types: ["opened", "synchronize", "reopened"]

env:
    PYCURL_SSL_LIBRARY: openssl

jobs:
  codechecks:
    name: Code Quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
    steps:
      - name: Checkout Nailgun
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set Up Python-${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt-get install -y libgnutls28-dev libcurl4-openssl-dev libssl-dev
          # link vs compile time ssl implementations can break the environment when installing requirements
          # Uninstall pycurl - its likely not installed, but in case the ubuntu-latest packages change
          # Then compile and install it with PYCURL_SSL_LIBRARY set to openssl
          pip install -U pip
          pip uninstall -y pycurl
          pip install --compile --no-cache-dir pycurl
          pip install -U -r requirements.txt -r requirements-dev.txt --no-cache-dir

      - name: Run Tests
        run: make test

      - name: Make Docs
        run: |
          make docs-html
          make docs-clean

      - name: Make Package
        run: |
          make package
          make package-clean

      - name: Analysis (git diff)
        if: failure()
        run: git diff

