# Github Action to Automatically assign T2 Reviewers to framework touched PRs
name: Tier2 Reviewers

on:
  pull_request:
    paths: ['*', '.github/**']

permissions:
  pull-requests: write

env:
  NUMBER: ${{ github.event.number }}
  REVIEWERS: '["robottelo-tier-2-reviewers"]'
  LABELS: '["Framework Changes"]'

jobs:
  assign-label-T2-reviewers:
    name: Assign Tier2 Reviewers to the PR
    runs-on: ubuntu-latest
    steps:
      - name: Add Labels to the PR
        run: |
          echo "Adding applicable labels to the PR $NUMBER"
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.CHERRYPICK_PAT }}" \
          https://api.github.com/repos/SatelliteQE/nailgun/issues/$NUMBER/labels \
          -d '{"labels": '"$LABELS"'}'
